//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPlanSwitcher.Translations {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerPlanSwitcher.Translations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;OK 的本地化字符串。
        /// </summary>
        internal static string AboutBox_OkButton {
            get {
                return ResourceManager.GetString("AboutBox_OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About {0} 的本地化字符串。
        /// </summary>
        internal static string AboutBox_TitleFormat {
            get {
                return ResourceManager.GetString("AboutBox_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version {0} 的本地化字符串。
        /// </summary>
        internal static string AboutBox_VersionFormat {
            get {
                return ResourceManager.GetString("AboutBox_VersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery Management 的本地化字符串。
        /// </summary>
        internal static string AppContext_ToastBatteryManagement {
            get {
                return ResourceManager.GetString("AppContext_ToastBatteryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule applied 的本地化字符串。
        /// </summary>
        internal static string AppContext_ToastRuleApplied {
            get {
                return ResourceManager.GetString("AppContext_ToastRuleApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Mode 的本地化字符串。
        /// </summary>
        internal static string ColorTheme_Dark {
            get {
                return ResourceManager.GetString("ColorTheme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Mode 的本地化字符串。
        /// </summary>
        internal static string ColorTheme_Light {
            get {
                return ResourceManager.GetString("ColorTheme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use System Setting 的本地化字符串。
        /// </summary>
        internal static string ColorTheme_System {
            get {
                return ResourceManager.GetString("ColorTheme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;No Name&gt; 的本地化字符串。
        /// </summary>
        internal static string Common_NoName {
            get {
                return ResourceManager.GetString("Common_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No rule active 的本地化字符串。
        /// </summary>
        internal static string Common_NoRuleActive {
            get {
                return ResourceManager.GetString("Common_NoRuleActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CreatePasswordDlg_BtnCancel {
            get {
                return ResourceManager.GetString("CreatePasswordDlg_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string CreatePasswordDlg_BtnOk {
            get {
                return ResourceManager.GetString("CreatePasswordDlg_BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To protect the ZIP file with encryption, enter a password.
        ///Leave the field empty to create an unencrypted archive. 的本地化字符串。
        /// </summary>
        internal static string CreatePasswordDlg_Hint {
            get {
                return ResourceManager.GetString("CreatePasswordDlg_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to copy to clipboard: {0} 的本地化字符串。
        /// </summary>
        internal static string CreatePasswordDlg_MsgCopyFailed {
            get {
                return ResourceManager.GetString("CreatePasswordDlg_MsgCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Password 的本地化字符串。
        /// </summary>
        internal static string CreatePasswordDlg_Title {
            get {
                return ResourceManager.GetString("CreatePasswordDlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard Error 的本地化字符串。
        /// </summary>
        internal static string CreatePasswordDlg_TitleClipboardError {
            get {
                return ResourceManager.GetString("CreatePasswordDlg_TitleClipboardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string HotkeySelectionDlg_BtnCancel {
            get {
                return ResourceManager.GetString("HotkeySelectionDlg_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string HotkeySelectionDlg_BtnOk {
            get {
                return ResourceManager.GetString("HotkeySelectionDlg_BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected Hotkey: 的本地化字符串。
        /// </summary>
        internal static string HotkeySelectionDlg_LblSelectedHotkey {
            get {
                return ResourceManager.GetString("HotkeySelectionDlg_LblSelectedHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerPlanSwitcher - Set Hotkey 的本地化字符串。
        /// </summary>
        internal static string HotkeySelectionDlg_Title {
            get {
                return ResourceManager.GetString("HotkeySelectionDlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_BtnCancel {
            get {
                return ResourceManager.GetString("IconSelectionDlg_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_BtnOk {
            get {
                return ResourceManager.GetString("IconSelectionDlg_BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select from file... 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_BtnSelectFile {
            get {
                return ResourceManager.GetString("IconSelectionDlg_BtnSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_FilterAllFiles {
            get {
                return ResourceManager.GetString("IconSelectionDlg_FilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All image types (*.png; *.jpg; *.jpeg; *.bmp; *.tiff; *.tif; *.gif)|*.png;*.jpg;*.jpeg;*.bmp;*.tiff;*.tif;*.gif 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_FilterAllImages {
            get {
                return ResourceManager.GetString("IconSelectionDlg_FilterAllImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BMP (*.bmp)|*.bmp 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_FilterBmp {
            get {
                return ResourceManager.GetString("IconSelectionDlg_FilterBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GIF (*.gif)|*.gif 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_FilterGif {
            get {
                return ResourceManager.GetString("IconSelectionDlg_FilterGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JPEG (*.jpg; *.jpeg)|*.jpg;*.jpeg 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_FilterJpeg {
            get {
                return ResourceManager.GetString("IconSelectionDlg_FilterJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG (*.png)|*.png 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_FilterPng {
            get {
                return ResourceManager.GetString("IconSelectionDlg_FilterPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TIFF (*.tiff; *.tif)|*.tiff;*.tif 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_FilterTiff {
            get {
                return ResourceManager.GetString("IconSelectionDlg_FilterTiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter: 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_LblFilter {
            get {
                return ResourceManager.GetString("IconSelectionDlg_LblFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected file could not be loaded as an icon image. Please choose a valid PNG, JPG, BMP, TIFF, or GIF image. 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_MsgInvalidImage {
            get {
                return ResourceManager.GetString("IconSelectionDlg_MsgInvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid image file 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_MsgInvalidImageTitle {
            get {
                return ResourceManager.GetString("IconSelectionDlg_MsgInvalidImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerPlanSwitcher - Icon selection 的本地化字符串。
        /// </summary>
        internal static string IconSelectionDlg_Title {
            get {
                return ResourceManager.GetString("IconSelectionDlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevent idle when another process set any of these Execution States:
        ///- ES_AWAYMODE_REQUIRED Forces the system to continue running critical background processes.
        ///- ES_DISPLAY_REQUIRED Forces the display to be on by resetting the display idle timer.
        ///- ES_SYSTEM_REQUIRED Forces the system to be in the working state by resetting the system idle timer. 的本地化字符串。
        /// </summary>
        internal static string IdleRuleControl_ExecutionStateHint {
            get {
                return ResourceManager.GetString("IdleRuleControl_ExecutionStateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevent idle when the active process is running in fullscreen mode. 的本地化字符串。
        /// </summary>
        internal static string IdleRuleControl_FullscreenAppHint {
            get {
                return ResourceManager.GetString("IdleRuleControl_FullscreenAppHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Execution State: 的本地化字符串。
        /// </summary>
        internal static string IdleRuleControl_LblCheckExecutionState {
            get {
                return ResourceManager.GetString("IdleRuleControl_LblCheckExecutionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Fullscreen Apps: 的本地化字符串。
        /// </summary>
        internal static string IdleRuleControl_LblCheckFullscreenApp {
            get {
                return ResourceManager.GetString("IdleRuleControl_LblCheckFullscreenApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle Time Threshold: 的本地化字符串。
        /// </summary>
        internal static string IdleRuleControl_LblIdleTimeThreshold {
            get {
                return ResourceManager.GetString("IdleRuleControl_LblIdleTimeThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hours 的本地化字符串。
        /// </summary>
        internal static string IdleRuleControl_UnitHours {
            get {
                return ResourceManager.GetString("IdleRuleControl_UnitHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minutes 的本地化字符串。
        /// </summary>
        internal static string IdleRuleControl_UnitMinutes {
            get {
                return ResourceManager.GetString("IdleRuleControl_UnitMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seconds 的本地化字符串。
        /// </summary>
        internal static string IdleRuleControl_UnitSeconds {
            get {
                return ResourceManager.GetString("IdleRuleControl_UnitSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About... 的本地化字符串。
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Active)  的本地化字符串。
        /// </summary>
        internal static string Menu_ActivePrefix {
            get {
                return ResourceManager.GetString("Menu_ActivePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close PowerPlanSwitcher 的本地化字符串。
        /// </summary>
        internal static string Menu_Close {
            get {
                return ResourceManager.GetString("Menu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open settings... 的本地化字符串。
        /// </summary>
        internal static string Menu_OpenSettings {
            get {
                return ResourceManager.GetString("Menu_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom Right 的本地化字符串。
        /// </summary>
        internal static string PopUpLocation_BottomRight {
            get {
                return ResourceManager.GetString("PopUpLocation_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        internal static string PopUpLocation_Center {
            get {
                return ResourceManager.GetString("PopUpLocation_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string PopUpLocation_Off {
            get {
                return ResourceManager.GetString("PopUpLocation_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use System Setting 的本地化字符串。
        /// </summary>
        internal static string PopUpLocation_System {
            get {
                return ResourceManager.GetString("PopUpLocation_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Line Status: 的本地化字符串。
        /// </summary>
        internal static string PowerLineRuleControl_LblPowerLineStatus {
            get {
                return ResourceManager.GetString("PowerLineRuleControl_LblPowerLineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select File... 的本地化字符串。
        /// </summary>
        internal static string ProcessRuleControl_BtnSelectFile {
            get {
                return ResourceManager.GetString("ProcessRuleControl_BtnSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Folder... 的本地化字符串。
        /// </summary>
        internal static string ProcessRuleControl_BtnSelectFolder {
            get {
                return ResourceManager.GetString("ProcessRuleControl_BtnSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select from active Process... 的本地化字符串。
        /// </summary>
        internal static string ProcessRuleControl_BtnSelectFromProcess {
            get {
                return ResourceManager.GetString("ProcessRuleControl_BtnSelectFromProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The processes execution path has to end with the provided pattern.
        ///Ignoring case. 的本地化字符串。
        /// </summary>
        internal static string ProcessRuleControl_CmpEndsWithTip {
            get {
                return ResourceManager.GetString("ProcessRuleControl_CmpEndsWithTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The processes execution path has to match the pattern completely.
        ///Ignoring case. 的本地化字符串。
        /// </summary>
        internal static string ProcessRuleControl_CmpExactTip {
            get {
                return ResourceManager.GetString("ProcessRuleControl_CmpExactTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The processes execution path has to start with the provided pattern.
        ///Ignoring case. 的本地化字符串。
        /// </summary>
        internal static string ProcessRuleControl_CmpStartsWithTip {
            get {
                return ResourceManager.GetString("ProcessRuleControl_CmpStartsWithTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The process&apos;s execution path must match the provided wildcard pattern, using glob-style matching.
        ///Supports * (match within one folder), ? (single character), and ** (match across any number of folders).
        ///C:\Program Files\*.exe -&gt; matches any exe files directly in C:\Program Files
        ///C:\Program Files\**\*.exe -&gt; matches any exe files in any subfolder of C:\Program Files
        ///C:\Program Files\My?pp.exe -&gt; matches MyApp.exe and MySpp.exe in C:\Program Files
        ///Ignoring case. 的本地化字符串。
        /// </summary>
        internal static string ProcessRuleControl_CmpWildcardTip {
            get {
                return ResourceManager.GetString("ProcessRuleControl_CmpWildcardTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comparison: 的本地化字符串。
        /// </summary>
        internal static string ProcessRuleControl_LblComparison {
            get {
                return ResourceManager.GetString("ProcessRuleControl_LblComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pattern: 的本地化字符串。
        /// </summary>
        internal static string ProcessRuleControl_LblPattern {
            get {
                return ResourceManager.GetString("ProcessRuleControl_LblPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ProcessSelectionDlg_BtnCancel {
            get {
                return ResourceManager.GetString("ProcessSelectionDlg_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string ProcessSelectionDlg_BtnOk {
            get {
                return ResourceManager.GetString("ProcessSelectionDlg_BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string ProcessSelectionDlg_DgcName {
            get {
                return ResourceManager.GetString("ProcessSelectionDlg_DgcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        internal static string ProcessSelectionDlg_DgcPath {
            get {
                return ResourceManager.GetString("ProcessSelectionDlg_DgcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PID 的本地化字符串。
        /// </summary>
        internal static string ProcessSelectionDlg_DgcPid {
            get {
                return ResourceManager.GetString("ProcessSelectionDlg_DgcPid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Time 的本地化字符串。
        /// </summary>
        internal static string ProcessSelectionDlg_DgcStartTime {
            get {
                return ResourceManager.GetString("ProcessSelectionDlg_DgcStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerPlanSwitcher - Select Process 的本地化字符串。
        /// </summary>
        internal static string ProcessSelectionDlg_Title {
            get {
                return ResourceManager.GetString("ProcessSelectionDlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zip Files (*.zip)|*.zip|7zip Files (*.7z)|*.7z 的本地化字符串。
        /// </summary>
        internal static string Program_ExportLogFilter {
            get {
                return ResourceManager.GetString("Program_ExportLogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Log 的本地化字符串。
        /// </summary>
        internal static string Program_ExportLogTitle {
            get {
                return ResourceManager.GetString("Program_ExportLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to open log path: {0} 的本地化字符串。
        /// </summary>
        internal static string Program_OpenLogPathFailed {
            get {
                return ResourceManager.GetString("Program_OpenLogPathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open log path 的本地化字符串。
        /// </summary>
        internal static string Program_OpenLogPathTitle {
            get {
                return ResourceManager.GetString("Program_OpenLogPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cycle hotkey pressed 的本地化字符串。
        /// </summary>
        internal static string Program_ToastCycleHotkey {
            get {
                return ResourceManager.GetString("Program_ToastCycleHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Plan hotkey pressed 的本地化字符串。
        /// </summary>
        internal static string Program_ToastDirectHotkey {
            get {
                return ResourceManager.GetString("Program_ToastDirectHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_BtnCancel {
            get {
                return ResourceManager.GetString("RuleDlg_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_BtnOk {
            get {
                return ResourceManager.GetString("RuleDlg_BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Plan: 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_LblPowerScheme {
            get {
                return ResourceManager.GetString("RuleDlg_LblPowerScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Rule Type: 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_LblRuleType {
            get {
                return ResourceManager.GetString("RuleDlg_LblRuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid input 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_MsgInvalidInputTitle {
            get {
                return ResourceManager.GetString("RuleDlg_MsgInvalidInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a Rule Type! 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_MsgSelectRuleType {
            get {
                return ResourceManager.GetString("RuleDlg_MsgSelectRuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An idle rule switches power plans based on the duration without user input. 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_TipIdle {
            get {
                return ResourceManager.GetString("RuleDlg_TipIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A power line rule switches power plans based on the current power line status (plugged in or on battery). 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_TipPowerLine {
            get {
                return ResourceManager.GetString("RuleDlg_TipPowerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A process rule switches power plans based on the presence of a specified process running on the system. 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_TipProcess {
            get {
                return ResourceManager.GetString("RuleDlg_TipProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A shutdown rule switches power plans when the system is shutting down. 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_TipShutdown {
            get {
                return ResourceManager.GetString("RuleDlg_TipShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A startup rule switches power plans when the system starts up.
        ///Optionally, you can set a duration after which the power scheme will be deactivated.
        ///This rule is always triggered and should be the last rule in the list. 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_TipStartup {
            get {
                return ResourceManager.GetString("RuleDlg_TipStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerPlanSwitcher - Rule 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_Title {
            get {
                return ResourceManager.GetString("RuleDlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle Rule 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_TypeIdle {
            get {
                return ResourceManager.GetString("RuleDlg_TypeIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Line Rule 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_TypePowerLine {
            get {
                return ResourceManager.GetString("RuleDlg_TypePowerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Rule 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_TypeProcess {
            get {
                return ResourceManager.GetString("RuleDlg_TypeProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutdown Rule 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_TypeShutdown {
            get {
                return ResourceManager.GetString("RuleDlg_TypeShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup Rule 的本地化字符串。
        /// </summary>
        internal static string RuleDlg_TypeStartup {
            get {
                return ResourceManager.GetString("RuleDlg_TypeStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create new Rule 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnAddPowerRule {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnAddPowerRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Rule up
        ///(higher priority) 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnAscentPowerRule {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnAscentPowerRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Plan up 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnAscentPowerScheme {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnAscentPowerScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete selected Rule 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnDeletePowerRule {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnDeletePowerRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Rule down
        ///(lower priority) 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnDescentPowerRule {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnDescentPowerRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Plan down 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnDescentPowerScheme {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnDescentPowerScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit selected Rule 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnEditPowerRule {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnEditPowerRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export log to zip 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnExportLog {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnExportLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open log folder 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnOpenLogFolder {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnOpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open power plan
        ///settings 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnOpenPowerPlanSettings {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnOpenPowerPlanSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Hotkey 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnRemoveCycleHotkey {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnRemoveCycleHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Hotkey 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnRemoveHotkey {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnRemoveHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Icon 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnRemoveIcon {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnRemoveIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Hotkey 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnSetCycleHotkey {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnSetCycleHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Hotkey 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnSetHotkey {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnSetHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Icon 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_BtnSetIcon {
            get {
                return ResourceManager.GetString("SettingsDlg_BtnSetIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extended Logging 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_ChbExtendedLogging {
            get {
                return ResourceManager.GetString("SettingsDlg_ChbExtendedLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_DgcHotkey {
            get {
                return ResourceManager.GetString("SettingsDlg_DgcHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_DgcIcon {
            get {
                return ResourceManager.GetString("SettingsDlg_DgcIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_DgcName {
            get {
                return ResourceManager.GetString("SettingsDlg_DgcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_DgcRuleDescription {
            get {
                return ResourceManager.GetString("SettingsDlg_DgcRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_DgcRulePriority {
            get {
                return ResourceManager.GetString("SettingsDlg_DgcRulePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Plan 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_DgcRuleSchemeName {
            get {
                return ResourceManager.GetString("SettingsDlg_DgcRuleSchemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_DgcTriggerCount {
            get {
                return ResourceManager.GetString("SettingsDlg_DgcTriggerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visible 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_DgcVisible {
            get {
                return ResourceManager.GetString("SettingsDlg_DgcVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Theme 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_GroupColorTheme {
            get {
                return ResourceManager.GetString("SettingsDlg_GroupColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey to cycle through Power Plans 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_GroupHotkeyCycle {
            get {
                return ResourceManager.GetString("SettingsDlg_GroupHotkeyCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_GroupLogging {
            get {
                return ResourceManager.GetString("SettingsDlg_GroupLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notification Location 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_GroupNotificationLocation {
            get {
                return ResourceManager.GetString("SettingsDlg_GroupNotificationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule order matters: rules are evaluated top to bottom, and the first triggered rule is applied. 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_LblRulesOrderHint {
            get {
                return ResourceManager.GetString("SettingsDlg_LblRulesOrderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regular logging only captures critical errors, such as crash-related exceptions.
        ///Extended logging may have performance implication.
        ///Extended log files will include basic information about running processes 
        ///(process ID, executable path and start/stop times) 
        ///which may be considered sensitive data. 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_LoggingHint {
            get {
                return ResourceManager.GetString("SettingsDlg_LoggingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not open Windows power plan settings. 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_MsgCouldNotOpenSettings {
            get {
                return ResourceManager.GetString("SettingsDlg_MsgCouldNotOpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey already assigned to cycle through Power Plans.
        ///Do you want to rebind to &apos;{0}&apos;? 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_MsgHotkeyAlreadyAssignedToCycle {
            get {
                return ResourceManager.GetString("SettingsDlg_MsgHotkeyAlreadyAssignedToCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey already assigned to Power Plan &apos;{0}&apos;.
        ///Do you want to rebind to &apos;{1}&apos;? 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_MsgHotkeyAlreadyAssignedToPlan {
            get {
                return ResourceManager.GetString("SettingsDlg_MsgHotkeyAlreadyAssignedToPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected entry is not a valid power plan. 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_MsgNotValidPowerPlan {
            get {
                return ResourceManager.GetString("SettingsDlg_MsgNotValidPowerPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a power plan first. 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_MsgSelectPowerPlanFirst {
            get {
                return ResourceManager.GetString("SettingsDlg_MsgSelectPowerPlanFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cycle through all existing Power Plans 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_RdbCycleAll {
            get {
                return ResourceManager.GetString("SettingsDlg_RdbCycleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cycle only through visible Power Plans 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_RdbCycleVisible {
            get {
                return ResourceManager.GetString("SettingsDlg_RdbCycleVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rules are evaluated from top to bottom.
        ///The first currently triggered rule is applied.
        ///Move Rule up/down to change priority. 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_RulesOrderHint {
            get {
                return ResourceManager.GetString("SettingsDlg_RulesOrderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Settings 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_TabOtherSettings {
            get {
                return ResourceManager.GetString("SettingsDlg_TabOtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Plans 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_TabPowerSchemes {
            get {
                return ResourceManager.GetString("SettingsDlg_TabPowerSchemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rules 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_TabRules {
            get {
                return ResourceManager.GetString("SettingsDlg_TabRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerPlanSwitcher - Settings 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_Title {
            get {
                return ResourceManager.GetString("SettingsDlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey already in use 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_TitleHotkeyAlreadyInUse {
            get {
                return ResourceManager.GetString("SettingsDlg_TitleHotkeyAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open power plan settings 的本地化字符串。
        /// </summary>
        internal static string SettingsDlg_TitleOpenPowerPlanSettings {
            get {
                return ResourceManager.GetString("SettingsDlg_TitleOpenPowerPlanSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When enabled, triggering of this Startup Rule is postponed by the configured delay after monitoring starts.
        ///If you also enable a duration, the countdown for that duration begins only when the rule actually becomes triggered (after the delay). 的本地化字符串。
        /// </summary>
        internal static string StartupRuleControl_DelayHint {
            get {
                return ResourceManager.GetString("StartupRuleControl_DelayHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable this option to automatically untrigger this Startup Rule after the specified duration.
        ///If disabled, the Startup Rule remains triggered indefinitely once it has triggered. 的本地化字符串。
        /// </summary>
        internal static string StartupRuleControl_DurationHint {
            get {
                return ResourceManager.GetString("StartupRuleControl_DurationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay: 的本地化字符串。
        /// </summary>
        internal static string StartupRuleControl_LblDelay {
            get {
                return ResourceManager.GetString("StartupRuleControl_LblDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration: 的本地化字符串。
        /// </summary>
        internal static string StartupRuleControl_LblDuration {
            get {
                return ResourceManager.GetString("StartupRuleControl_LblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Delay: 的本地化字符串。
        /// </summary>
        internal static string StartupRuleControl_LblEnableDelay {
            get {
                return ResourceManager.GetString("StartupRuleControl_LblEnableDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Duration: 的本地化字符串。
        /// </summary>
        internal static string StartupRuleControl_LblEnableDuration {
            get {
                return ResourceManager.GetString("StartupRuleControl_LblEnableDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hours 的本地化字符串。
        /// </summary>
        internal static string StartupRuleControl_UnitHours {
            get {
                return ResourceManager.GetString("StartupRuleControl_UnitHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minutes 的本地化字符串。
        /// </summary>
        internal static string StartupRuleControl_UnitMinutes {
            get {
                return ResourceManager.GetString("StartupRuleControl_UnitMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seconds 的本地化字符串。
        /// </summary>
        internal static string StartupRuleControl_UnitSeconds {
            get {
                return ResourceManager.GetString("StartupRuleControl_UnitSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerPlanSwitcher switched Power Plan to: 的本地化字符串。
        /// </summary>
        internal static string ToastDlg_Title {
            get {
                return ResourceManager.GetString("ToastDlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerPlan 的本地化字符串。
        /// </summary>
        internal static string Tray_Tooltip_PowerPlan {
            get {
                return ResourceManager.GetString("Tray_Tooltip_PowerPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule 的本地化字符串。
        /// </summary>
        internal static string Tray_Tooltip_Rule {
            get {
                return ResourceManager.GetString("Tray_Tooltip_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerPlanSwitcher 的本地化字符串。
        /// </summary>
        internal static string Tray_Tooltip_Title {
            get {
                return ResourceManager.GetString("Tray_Tooltip_Title", resourceCulture);
            }
        }
    }
}
