//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuleManagement.Translations {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RuleManagement.Translations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Idle Time -&gt; {0} 的本地化字符串。
        /// </summary>
        internal static string Rule_Idle_Desc {
            get {
                return ResourceManager.GetString("Rule_Idle_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Line -&gt; {0} 的本地化字符串。
        /// </summary>
        internal static string Rule_PowerLine_Desc {
            get {
                return ResourceManager.GetString("Rule_PowerLine_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On battery 的本地化字符串。
        /// </summary>
        internal static string Rule_PowerLine_Offline {
            get {
                return ResourceManager.GetString("Rule_PowerLine_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugged in 的本地化字符串。
        /// </summary>
        internal static string Rule_PowerLine_Online {
            get {
                return ResourceManager.GetString("Rule_PowerLine_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unkown status 的本地化字符串。
        /// </summary>
        internal static string Rule_PowerLine_Unknown {
            get {
                return ResourceManager.GetString("Rule_PowerLine_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path ends with 的本地化字符串。
        /// </summary>
        internal static string Rule_Process_CmpEndsWith {
            get {
                return ResourceManager.GetString("Rule_Process_CmpEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match exact Path 的本地化字符串。
        /// </summary>
        internal static string Rule_Process_CmpExact {
            get {
                return ResourceManager.GetString("Rule_Process_CmpExact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path starts with 的本地化字符串。
        /// </summary>
        internal static string Rule_Process_CmpStartsWith {
            get {
                return ResourceManager.GetString("Rule_Process_CmpStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wildcard match 的本地化字符串。
        /// </summary>
        internal static string Rule_Process_CmpWildcard {
            get {
                return ResourceManager.GetString("Rule_Process_CmpWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process -&gt; {0} -&gt; {1} 的本地化字符串。
        /// </summary>
        internal static string Rule_Process_Desc {
            get {
                return ResourceManager.GetString("Rule_Process_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutdown Rule 的本地化字符串。
        /// </summary>
        internal static string Rule_Shutdown_Desc {
            get {
                return ResourceManager.GetString("Rule_Shutdown_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delay {0} 的本地化字符串。
        /// </summary>
        internal static string Rule_Startup_Delay {
            get {
                return ResourceManager.GetString("Rule_Startup_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup Rule ({0}, {1}) 的本地化字符串。
        /// </summary>
        internal static string Rule_Startup_Desc_DelayDuration {
            get {
                return ResourceManager.GetString("Rule_Startup_Desc_DelayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup Rule ({0}) 的本地化字符串。
        /// </summary>
        internal static string Rule_Startup_Desc_OnlyDelay {
            get {
                return ResourceManager.GetString("Rule_Startup_Desc_OnlyDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 duration {0} 的本地化字符串。
        /// </summary>
        internal static string Rule_Startup_Duration {
            get {
                return ResourceManager.GetString("Rule_Startup_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} hour 的本地化字符串。
        /// </summary>
        internal static string Rule_Startup_Hour {
            get {
                return ResourceManager.GetString("Rule_Startup_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} hours 的本地化字符串。
        /// </summary>
        internal static string Rule_Startup_Hours {
            get {
                return ResourceManager.GetString("Rule_Startup_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} minute 的本地化字符串。
        /// </summary>
        internal static string Rule_Startup_Minute {
            get {
                return ResourceManager.GetString("Rule_Startup_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} minutes 的本地化字符串。
        /// </summary>
        internal static string Rule_Startup_Minutes {
            get {
                return ResourceManager.GetString("Rule_Startup_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup Rule 的本地化字符串。
        /// </summary>
        internal static string Rule_Startup_Name {
            get {
                return ResourceManager.GetString("Rule_Startup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} second 的本地化字符串。
        /// </summary>
        internal static string Rule_Startup_Second {
            get {
                return ResourceManager.GetString("Rule_Startup_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} seconds 的本地化字符串。
        /// </summary>
        internal static string Rule_Startup_Seconds {
            get {
                return ResourceManager.GetString("Rule_Startup_Seconds", resourceCulture);
            }
        }
    }
}
